# Generated by Django 3.1.7 on 2021-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('father_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('pin_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('class_opted', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
                ('marks', models.CharField(max_length=100)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
